[package]
name = "cr8s-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
web-sys = {version = "0.3", features =["HtmlInputElement"] }
gloo-console = "0.2"